import 'dart:async';
import 'dart:convert';
import 'package:flutter/foundation.dart';
import 'package:http/http.dart' as http;
import '../config/api_keys.dart';
import '../utils/romaji_converter.dart';
import 'adaptive_conversation.dart';

/// A suggestion generated by Claude (or fallback engine).
class AiSuggestion {
  final String japanese;
  final String romaji;
  final String english;
  const AiSuggestion({
    required this.japanese,
    required this.romaji,
    required this.english,
  });
}

/// Parsed response from Claude API (or fallback).
class ClaudeResponse {
  final String message;
  final String english;
  final bool corrected;
  final bool isEnd;
  final List<AiSuggestion> suggestions;

  const ClaudeResponse({
    required this.message,
    this.english = '',
    this.corrected = false,
    this.isEnd = false,
    this.suggestions = const [],
  });
}

/// Manages Claude API calls for natural Kuma-san conversations.
/// Falls back to [AdaptiveConversation] when offline or no API key.
class ClaudeApiService {
  static const String _apiUrl = 'https://api.anthropic.com/v1/messages';
  static const String _model = 'claude-sonnet-4-5-20250929';
  static const int _maxTokens = 800;
  static const int _maxHistory = 20;

  final String topicId;
  final String topicName;
  final String userLevel;

  final List<Map<String, String>> _history = [];
  late final AdaptiveConversation _fallback;

  int _turnCount = 0;
  int correctionsCount = 0;
  int japaneseCharsTyped = 0;
  int _totalInputs = 0;

  bool get hasApiKey =>
      ApiKeys.claudeApiKey.isNotEmpty &&
      ApiKeys.claudeApiKey != 'YOUR_API_KEY_HERE';

  bool get isUsingAi => hasApiKey;

  /// Whether the last response actually came from Claude (not fallback).
  bool lastWasAiResponse = false;

  /// Last error message (for debugging).
  String? lastError;

  ClaudeApiService({
    required this.topicId,
    required this.topicName,
    this.userLevel = 'beginner',
  }) {
    _fallback = AdaptiveConversation(topicId: topicId);
  }

  // ==========================================
  // PUBLIC API
  // ==========================================

  /// Get Kuma's opening message for this topic.
  Future<ClaudeResponse> getOpeningMessage() async {
    if (!hasApiKey) {
      debugPrint('🐻 No API key — using fallback');
      lastWasAiResponse = false;
      return _fallbackOpening();
    }
    try {
      final result = await _callApi(
        'Start our conversation about "$topicName". '
        'Give a short, friendly greeting and ask an opening question.',
      );
      lastWasAiResponse = true;
      lastError = null;
      debugPrint('🐻 Opening from Claude AI');
      return result;
    } catch (e) {
      lastWasAiResponse = false;
      lastError = e.toString();
      debugPrint('🐻 Opening FAILED, using fallback: $e');
      return _fallbackOpening();
    }
  }

  /// Send user message and get Kuma's AI response.
  Future<ClaudeResponse> sendMessage(String userMessage) async {
    _totalInputs++;
    _turnCount++;
    japaneseCharsTyped += RomajiConverter.countJapaneseChars(userMessage);

    if (!hasApiKey) {
      debugPrint('🐻 No API key — using fallback');
      lastWasAiResponse = false;
      return _fallbackResponse(userMessage);
    }

    try {
      final result = await _callApi(userMessage);
      lastWasAiResponse = true;
      lastError = null;
      debugPrint('🐻 Response from Claude AI (turn $_turnCount)');
      return result;
    } catch (e) {
      lastWasAiResponse = false;
      lastError = e.toString();
      debugPrint('🐻 API FAILED, using fallback: $e');
      return _fallbackResponse(userMessage);
    }
  }

  /// Static hints from the fallback engine (for the hint sheet).
  List<AiSuggestion> getStaticHints() {
    return _fallback
        .getHints()
        .map((h) => AiSuggestion(
              japanese: h.japanese,
              romaji: h.romaji,
              english: h.english,
            ))
        .toList();
  }

  /// Accuracy score (0.0 to 1.0).
  double get accuracyScore {
    if (_totalInputs == 0) return 1.0;
    return (1.0 - (correctionsCount / _totalInputs)).clamp(0.0, 1.0);
  }

  void reset() {
    _history.clear();
    _fallback.reset();
    _turnCount = 0;
    correctionsCount = 0;
    japaneseCharsTyped = 0;
    _totalInputs = 0;
    lastWasAiResponse = false;
    lastError = null;
  }

  // ==========================================
  // API CALL
  // ==========================================

  Future<ClaudeResponse> _callApi(String userMessage) async {
    _history.add({'role': 'user', 'content': userMessage});

    // Keep history within limits for efficient API calls
    final messages = _history.length > _maxHistory
        ? _history.sublist(_history.length - _maxHistory)
        : List<Map<String, String>>.from(_history);

    debugPrint('🔍 API call: ${messages.length} messages, model=$_model');
    debugPrint('🔍 Last user msg: $userMessage');

    final response = await http
        .post(
          Uri.parse(_apiUrl),
          headers: {
            'Content-Type': 'application/json',
            'x-api-key': ApiKeys.claudeApiKey,
            'anthropic-version': '2023-06-01',
            'anthropic-dangerous-direct-browser-access': 'true',
          },
          body: jsonEncode({
            'model': _model,
            'max_tokens': _maxTokens,
            'system': _systemPrompt(),
            'messages': messages,
          }),
        )
        .timeout(const Duration(seconds: 30));

    debugPrint('📥 API status: ${response.statusCode}');

    if (response.statusCode != 200) {
      debugPrint('❌ API error body: ${response.body}');
      throw Exception('API error ${response.statusCode}: ${response.body}');
    }

    final data = jsonDecode(response.body) as Map<String, dynamic>;
    final text = (data['content'] as List).first['text'] as String;

    debugPrint('🐻 Claude response: ${text.substring(0, text.length.clamp(0, 100))}...');

    // Add assistant response to conversation history
    _history.add({'role': 'assistant', 'content': text});

    return _parseResponse(text);
  }

  // ==========================================
  // RESPONSE PARSING
  // ==========================================

  ClaudeResponse _parseResponse(String raw) {
    try {
      String jsonStr = raw.trim();

      // Strip markdown code fences if Claude wraps JSON in them
      if (jsonStr.contains('```')) {
        final match =
            RegExp(r'```(?:json)?\s*([\s\S]*?)```').firstMatch(jsonStr);
        if (match != null) jsonStr = match.group(1)!.trim();
      }

      final json = jsonDecode(jsonStr) as Map<String, dynamic>;

      final corrected = json['corrected'] as bool? ?? false;
      if (corrected) correctionsCount++;

      final suggestionsRaw = json['suggestions'] as List? ?? [];
      final suggestions = suggestionsRaw
          .cast<Map<String, dynamic>>()
          .map((s) => AiSuggestion(
                japanese: s['jp'] as String? ?? '',
                romaji: s['romaji'] as String? ?? '',
                english: s['en'] as String? ?? '',
              ))
          .where((s) => s.japanese.isNotEmpty)
          .toList();

      final isEnd = json['isEnd'] as bool? ?? (_turnCount >= 10);

      return ClaudeResponse(
        message: json['message'] as String? ?? raw,
        english: json['english'] as String? ?? '',
        corrected: corrected,
        isEnd: isEnd,
        suggestions: suggestions,
      );
    } catch (_) {
      // JSON parsing failed — use raw text as message
      return ClaudeResponse(
        message: raw,
        isEnd: _turnCount >= 10,
      );
    }
  }

  // ==========================================
  // SYSTEM PROMPT
  // ==========================================

  String _systemPrompt() {
    final isWrappingUp = _turnCount >= 8;

    return '''You are Kuma-san (くまさん), a friendly Japanese bear tutor having a REAL conversation.

PERSONALITY:
- Warm, encouraging, patient, playful
- Mix Japanese and English naturally
- Use emojis sparingly (🐻 🌟 💪 😊)
- Never harsh — always supportive

CONTEXT:
- Topic: $topicName
- User level: $userLevel
- Turn: $_turnCount of 10${isWrappingUp ? '\n- WRAPPING UP: Bring the conversation to a natural close.' : ''}

CRITICAL RULES — FOLLOW STRICTLY:
1. READ the user's ACTUAL message before replying
2. ACKNOWLEDGE what they said — reference their specific words
3. CORRECT any Japanese mistakes (particles, grammar, spelling) — ALWAYS
4. Ask a NEW follow-up question — NEVER repeat a question you already asked
5. Move the conversation forward naturally

CORRECTION EXAMPLES:
User: "わたしわ simon desu"
→ Acknowledge: "Simon-san! 😊"
→ Correct: わたし**は** (は not わ — the particle is written は but pronounced wa)
→ Follow-up: "趣味は何ですか? What are your hobbies?"

User: "ぼくわ pc すき"
→ Acknowledge: "パソコンが好きなんですね! 💻"
→ Correct: ぼく**は** PC**が** 好き**です** (は particle, が for objects of 好き, です for politeness)
→ Follow-up: "What do you do on PC? ゲーム? プログラミング?"

User: "meat and rice"
→ Talk about BOTH meat AND rice, never ignore part of what they said
→ Teach: 肉 (niku) と ご飯 (gohan)!

RESPONSE FORMAT — Respond with ONLY valid JSON (no markdown, no extra text):
{
  "message": "Your natural response mixing Japanese and English",
  "english": "Full English translation of your response",
  "corrected": false,
  "suggestions": [
    {"jp": "Japanese phrase", "romaji": "romaji reading", "en": "English meaning"},
    {"jp": "Japanese phrase", "romaji": "romaji", "en": "English"},
    {"jp": "Japanese phrase", "romaji": "romaji", "en": "English"}
  ]${_turnCount >= 10 ? ',\n  "isEnd": true' : ''}
}

RULES:
- "message": 1-3 sentences, natural and engaging
- "corrected": true when you corrected ANY user mistake
- "suggestions": exactly 3, relevant to what you just asked, at $userLevel level
- NEVER repeat a question — always ask something NEW${_turnCount >= 10 ? '\n- This is the FINAL turn. Wrap up warmly. Set "isEnd": true.' : ''}''';
  }

  // ==========================================
  // FALLBACK (offline / no API key)
  // ==========================================

  ClaudeResponse _fallbackOpening() {
    final opening = _fallback.getOpeningMessage();
    return ClaudeResponse(
      message: opening.text,
      english: opening.english,
      suggestions: _fallbackSuggestions(),
    );
  }

  ClaudeResponse _fallbackResponse(String userMessage) {
    final response = _fallback.processInput(userMessage);
    correctionsCount = _fallback.correctionsCount;
    return ClaudeResponse(
      message: response.text,
      english: response.english,
      isEnd: response.isEnd,
      suggestions: _fallbackSuggestions(),
    );
  }

  List<AiSuggestion> _fallbackSuggestions() {
    return _fallback
        .getHints()
        .take(3)
        .map((h) => AiSuggestion(
              japanese: h.japanese,
              romaji: h.romaji,
              english: h.english,
            ))
        .toList();
  }
}
